require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'WBW' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'react-native-image-crop-tools', :path => '../node_modules/react-native-image-crop-tools'
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
